### ISSUE TITLE
关于自动连接的问题

### ISSUE THREAD

**Issue by qiuseruxin** [remember17/WHBLEDemo#1]
大神  我做手机连接手环,现在我想让APP每次打开自动连接之前连接过的手环,请问我需要怎么弄呢,是需要配对吗

**Comment by remember17** [comment]
通过peripheral.identifier.UUIDString记住UUIDString，下次启动的时候在centralManagerDidUpdateState方法里用centralManager的retrievePeripheralsWithIdentifiers方法来自动重连

**Comment by qiuseruxin** [comment]
感谢作者，受教了！

发自我的 iPhone

在 2017年8月18日，09:18，wuhao <notifications@github.com<mailto:notifications@github.com>> 写道：


通过peripheral.identifier.UUIDString记住UUIDString，下次启动的时候在centralManagerDidUpdateState方法里用centralManager的retrievePeripheralsWithIdentifiers方法来自动重连
